services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    ports:
      - "8090:8090"
    environment:
      - PB_HOST=0.0.0.0
      - PB_PORT=8090
      - PB_ADMIN_EMAIL=admin@yourdomain.com
      - PB_ADMIN_PASSWORD=admin@yourdomain.com
      - TZ=Asia/Kolkata
    volumes:
      - ./pb_data:/pb_data
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
    #   interval: 2s
    #   timeout: 2s
    #   retries: 30